APPLICATION = saul_list_all

BOARD ?= native

RIOTBASE ?= $(RIOT_BASE)

DEVELHELP ?= 1

USEMODULE += saul saul_default
# USEMODULE += lsm6dso

CFLAGS += -DAUTO_INIT_LED0
# CFLAGS += -DAUTO_INIT_LSM6DSO

RIOTBASE ?= $(RIOT_BASE)

include $(RIOTBASE)/Makefile.include
